version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
